name: Feature Request
description: Suggest a new feature
labels: feature

body:
  - type: markdown
    attributes:
      value: |
        # <span style="color:red">Do not submit feature requests here! It will get closed. Feature requests MUST be submitted at https://features.jellyfin.org/</span>
