name: build

on:
  push:
    branches:
      - master

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: npx ropm install
      - run: make release
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: Jellyfin-Roku-release-${{ github.sha }}
          path: ${{ github.workspace }}/out/staging
          if-no-files-found: error