name: build-dev

on:
  pull_request:
  push:
    branches:
      - master
      - "*.*.z"

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build app
        run: npm run build
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: Jellyfin-Roku-dev-${{ github.sha }}
          path: ${{ github.workspace }}/build/staging
          if-no-files-found: error
